# Generated by Django 4.0.4 on 2022-05-02 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(default=None, max_length=256)),
                ('first_name', models.CharField(default=None, max_length=256)),
                ('last_name', models.CharField(default=None, max_length=256)),
                ('email_address', models.EmailField(default=None, max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('eligible_for_insurance', models.CharField(default=None, max_length=3)),
                ('created_datetime', models.DateTimeField(default=None)),
            ],
        ),
    ]
